repos:
-   repo: local
    hooks:
    -   id: save-vs-code-extensions
        name: Save VS Code extensions
        entry: python VSCode/pre_commit_hook.py
        language: system
        stages: [pre-commit]
